trigger:
 branches:
  include:
    - master
    - stable/*
pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.7'
variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)" | "$(python.version)" | "$(Build.BuildNumber)"'
    restoreKeys: |
      pip | "$(Agent.OS)" | "$(python.version)"
      pip | "$(Agent.OS)"
      pip
    path: $(PIP_CACHE_DIR)
  displayName: Cache pip
- bash: |
    set -e
    python -m pip install --upgrade pip setuptools wheel virtualenv
    virtualenv /tmp/docs_build
    source /tmp/docs_build/bin/activate
    pip install -U qiskit jupyter sphinx nbsphinx sphinx_rtd_theme
    pip install -U qiskit-terra[visualization] cvxpy
    sudo apt-get install -y pandoc graphviz
  displayName: 'Install dependencies'
- bash: |
    set -e
    source /tmp/docs_build/bin/activate
    sphinx-build -b html . _build/html
  displayName: 'Build Docs'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '_build/html'
    archiveType: tar
    archiveFile: '$(Build.ArtifactStagingDirectory)/html_docs.tar.gz'
    verbose: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish docs'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'html_docs'
    Parallel: true
    ParallelCount: 8
